"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.6.
"""

from pathlib import Path
import os
import environ

# ====== Paths ======
BASE_DIR = Path(__file__).resolve().parent.parent

# ====== Environment ======
env = environ.Env(
    DEBUG=(bool, False)
)
# Leer variables desde archivo .env en la raíz del proyecto
environ.Env.read_env(os.path.join(BASE_DIR, ".env"))

# ====== Seguridad ======
SECRET_KEY = env("SECRET_KEY")  # ⚠️ definido en .env
DEBUG = env.bool("DEBUG", default=False)
ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=["localhost", "127.0.0.1"])

# ====== Aplicaciones ======
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "corsheaders",
    "backendapi",
]

# ====== Middleware ======
MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",  # 👈 CORS primero
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"

# ====== Templates ======
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"

# ====== Base de Datos (Supabase / PostgreSQL) ======
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "HOST": env("DB_HOST"),
        "PORT": env("DB_PORT"),
        "NAME": env("DB_NAME"),
        "USER": env("DB_USER"),
        "PASSWORD": env("DB_PASSWORD"),
    }
}

# ====== Validaciones de Password ======
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# ====== Internacionalización ======
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# ====== Archivos estáticos ======
STATIC_URL = "static/"

# ====== Primary Key por defecto ======
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ====== CORS ======
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5175",
    "http://127.0.0.1:5175",
]

# 👉 Si prefieres permitir todos los orígenes en desarrollo:
# CORS_ALLOW_ALL_ORIGINS = True
