// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArGQ0_xPm-zgQQu-G2doAlEUzDry1fYj4',
    appId: '1:965989513474:web:41283d02d686e75503aa1b',
    messagingSenderId: '965989513474',
    projectId: 'smartcondominium-df523',
    authDomain: 'smartcondominium-df523.firebaseapp.com',
    storageBucket: 'smartcondominium-df523.firebasestorage.app',
    measurementId: 'G-HKN9T6S8FQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUlqyU-DM0wAadGdTGeBz2PpafGYHGu0s',
    appId: '1:965989513474:android:c1588890407870be03aa1b',
    messagingSenderId: '965989513474',
    projectId: 'smartcondominium-df523',
    storageBucket: 'smartcondominium-df523.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLLSzmCeJaUMq1RV7vctK_V_Bf-Njb7Ac',
    appId: '1:965989513474:ios:b610bb5f0758da2a03aa1b',
    messagingSenderId: '965989513474',
    projectId: 'smartcondominium-df523',
    storageBucket: 'smartcondominium-df523.firebasestorage.app',
    iosBundleId: 'com.si2.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLLSzmCeJaUMq1RV7vctK_V_Bf-Njb7Ac',
    appId: '1:965989513474:ios:b610bb5f0758da2a03aa1b',
    messagingSenderId: '965989513474',
    projectId: 'smartcondominium-df523',
    storageBucket: 'smartcondominium-df523.firebasestorage.app',
    iosBundleId: 'com.si2.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArGQ0_xPm-zgQQu-G2doAlEUzDry1fYj4',
    appId: '1:965989513474:web:73582c1d3af94ff403aa1b',
    messagingSenderId: '965989513474',
    projectId: 'smartcondominium-df523',
    authDomain: 'smartcondominium-df523.firebaseapp.com',
    storageBucket: 'smartcondominium-df523.firebasestorage.app',
    measurementId: 'G-95HK227TSR',
  );

}