# Generated by Django 5.2.6 on 2025-09-16 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', 'XXXX_add_mfa_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermfaprofile',
            name='user_id',
            field=models.UUIDField(help_text='UUID del usuario de Supabase', primary_key=True, serialize=False),
        ),
    ]
