# Generated by Django 5.2.6 on 2025-09-16 20:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=14)),
            ],
            options={
                'db_table': 'multas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nro_casa', models.TextField(blank=True, null=True)),
                ('m2', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
            options={
                'db_table': 'propiedad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoMulta',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
            ],
            options={
                'db_table': 'tipo_multa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MFAAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField(help_text='UUID del usuario de Supabase')),
                ('email', models.EmailField(help_text='Email del usuario para referencia', max_length=254)),
                ('success', models.BooleanField(default=False)),
                ('method', models.CharField(choices=[('totp', 'TOTP'), ('backup', 'Backup Token'), ('setup', 'Setup')], max_length=10)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(default='0.0.0.0')),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Intento MFA',
                'verbose_name_plural': 'Intentos MFA',
                'db_table': 'mfa_attempts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MFASession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('user_id', models.UUIDField(help_text='UUID del usuario de Supabase')),
                ('email', models.EmailField(help_text='Email del usuario para referencia', max_length=254)),
                ('step', models.CharField(choices=[('pending_mfa', 'Pendiente MFA'), ('mfa_verified', 'MFA Verificado'), ('completed', 'Completado')], default='pending_mfa', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('ip_address', models.GenericIPAddressField(default='0.0.0.0')),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sesión MFA',
                'verbose_name_plural': 'Sesiones MFA',
                'db_table': 'mfa_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserMFAProfile',
            fields=[
                ('user_id', models.UUIDField(help_text='UUID del usuario de Supabase', primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text='Email del usuario para referencia', max_length=254)),
                ('totp_secret', models.CharField(blank=True, max_length=32, null=True)),
                ('mfa_enabled', models.BooleanField(default=False)),
                ('backup_tokens', models.JSONField(blank=True, default=list)),
                ('last_totp_used', models.CharField(blank=True, max_length=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Perfil MFA',
                'verbose_name_plural': 'Perfiles MFA',
                'db_table': 'user_mfa_profiles',
            },
        ),
        migrations.CreateModel(
            name='CargoMulta',
            fields=[
                ('cargo_id', models.BigIntegerField()),
                ('multa', models.ForeignKey(db_column='multa_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='cargos', serialize=False, to='backendapi.multa')),
            ],
            options={
                'db_table': 'cargo_multa',
                'managed': False,
            },
        ),
    ]
